package com.yodoo.rent.model;
// Generated 2007-8-11 20:41:48 by Hibernate Tools 3.2.0.b9


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HouseInfo generated by hbm2java
 */
public class HouseInfo  implements java.io.Serializable {


     private String id;
     private Integer version;
     private User user;
     private Date publishTime;
     private Float longitude;
     private Float latitude;
     private Integer province;
     private Integer city;
     private Integer area;
     private Integer rooms;
     private Integer price;
     private Date endTime;
     private Integer rentType;
     private String provider;
     private String phone;
     private String email;
     private String addressDetail;
     private String description;
     private Date updateTime;
     private Integer viewCount;
     private String sourceUrl;
     private String sourceProvider;
     private Integer providerType;
     private Set<Media> medias = new HashSet<Media>(0);

    public HouseInfo() {
    }

	
    public HouseInfo(User user, Date publishTime, Integer rentType, String provider) {
        this.user = user;
        this.publishTime = publishTime;
        this.rentType = rentType;
        this.provider = provider;
    }
    public HouseInfo(User user, Date publishTime, Float longitude, Float latitude, Integer province, Integer city, Integer area, Integer rooms, Integer price, Date endTime, Integer rentType, String provider, String phone, String email, String addressDetail, String description, Date updateTime, Integer viewCount, String sourceUrl, String sourceProvider, Integer providerType, Set<Media> medias) {
       this.user = user;
       this.publishTime = publishTime;
       this.longitude = longitude;
       this.latitude = latitude;
       this.province = province;
       this.city = city;
       this.area = area;
       this.rooms = rooms;
       this.price = price;
       this.endTime = endTime;
       this.rentType = rentType;
       this.provider = provider;
       this.phone = phone;
       this.email = email;
       this.addressDetail = addressDetail;
       this.description = description;
       this.updateTime = updateTime;
       this.viewCount = viewCount;
       this.sourceUrl = sourceUrl;
       this.sourceProvider = sourceProvider;
       this.providerType = providerType;
       this.medias = medias;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getPublishTime() {
        return this.publishTime;
    }
    
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Integer getProvince() {
        return this.province;
    }
    
    public void setProvince(Integer province) {
        this.province = province;
    }
    public Integer getCity() {
        return this.city;
    }
    
    public void setCity(Integer city) {
        this.city = city;
    }
    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }
    public Integer getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Integer rooms) {
        this.rooms = rooms;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Integer getRentType() {
        return this.rentType;
    }
    
    public void setRentType(Integer rentType) {
        this.rentType = rentType;
    }
    public String getProvider() {
        return this.provider;
    }
    
    public void setProvider(String provider) {
        this.provider = provider;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddressDetail() {
        return this.addressDetail;
    }
    
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
    public String getSourceUrl() {
        return this.sourceUrl;
    }
    
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }
    public String getSourceProvider() {
        return this.sourceProvider;
    }
    
    public void setSourceProvider(String sourceProvider) {
        this.sourceProvider = sourceProvider;
    }
    public Integer getProviderType() {
        return this.providerType;
    }
    
    public void setProviderType(Integer providerType) {
        this.providerType = providerType;
    }
    public Set<Media> getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set<Media> medias) {
        this.medias = medias;
    }




}


