package com.yodoo.rent.model;
// Generated 2007-8-8 15:49:53 by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * LocationCache generated by hbm2java
 */
public class LocationCache  implements java.io.Serializable {


     private String address;
     private String formatAddress;
     private Float longitude;
     private Float latitude;
     private Integer zoom;
     private Date updateTime;

    public LocationCache() {
    }

	
    public LocationCache(String address) {
        this.address = address;
    }
    public LocationCache(String address, String formatAddress, Float longitude, Float latitude, Integer zoom, Date updateTime) {
       this.address = address;
       this.formatAddress = formatAddress;
       this.longitude = longitude;
       this.latitude = latitude;
       this.zoom = zoom;
       this.updateTime = updateTime;
    }
   
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getFormatAddress() {
        return this.formatAddress;
    }
    
    public void setFormatAddress(String formatAddress) {
        this.formatAddress = formatAddress;
    }
    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }
    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    public Integer getZoom() {
        return this.zoom;
    }
    
    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


