package com.yodoo.rent.model;
// Generated 2007-9-11 22:38:38 by Hibernate Tools 3.2.0.b9



/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private String id;
     private City city;
     private String name;
     private float lat;
     private float lng;
     private Integer hitCount;
     private String tag;

    public Area() {
    }

	
    public Area(String id, City city, String name, float lat, float lng) {
        this.id = id;
        this.city = city;
        this.name = name;
        this.lat = lat;
        this.lng = lng;
    }
    public Area(String id, City city, String name, float lat, float lng, Integer hitCount, String tag) {
       this.id = id;
       this.city = city;
       this.name = name;
       this.lat = lat;
       this.lng = lng;
       this.hitCount = hitCount;
       this.tag = tag;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getLat() {
        return this.lat;
    }
    
    public void setLat(float lat) {
        this.lat = lat;
    }
    public float getLng() {
        return this.lng;
    }
    
    public void setLng(float lng) {
        this.lng = lng;
    }
    public Integer getHitCount() {
        return this.hitCount;
    }
    
    public void setHitCount(Integer hitCount) {
        this.hitCount = hitCount;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }




}


