package com.yodoo.rent.model;
// Generated 2007-8-11 20:41:48 by Hibernate Tools 3.2.0.b9



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private String role;
     private String name;
     private String description;

    public Role() {
    }

	
    public Role(String role, String name) {
        this.role = role;
        this.name = name;
    }
    public Role(String role, String name, String description) {
       this.role = role;
       this.name = name;
       this.description = description;
    }
   
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


