package com.yodoo.rent.model;
// Generated 2007-8-8 15:49:53 by Hibernate Tools 3.2.0.b9



/**
 * UserProfile generated by hbm2java
 */
public class UserProfile  implements java.io.Serializable {


     private String id;
     private User user;
     private String fullName;
     private String phoneNo;
     private String cellPhone;
     private String email;
     private String address;
     private Double longitude;
     private Double latitude;
     private boolean actived;

    public UserProfile() {
    }

	
    public UserProfile(User user, boolean actived) {
        this.user = user;
        this.actived = actived;
    }
    public UserProfile(User user, String fullName, String phoneNo, String cellPhone, String email, String address, Double longitude, Double latitude, boolean actived) {
       this.user = user;
       this.fullName = fullName;
       this.phoneNo = phoneNo;
       this.cellPhone = cellPhone;
       this.email = email;
       this.address = address;
       this.longitude = longitude;
       this.latitude = latitude;
       this.actived = actived;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public boolean isActived() {
        return this.actived;
    }
    
    public void setActived(boolean actived) {
        this.actived = actived;
    }




}


