package com.yodoo.rent.model;
// Generated 2007-9-22 10:24:22 by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * Talk generated by hbm2java
 */
public class Talk  implements java.io.Serializable {


     private Integer id;
     private String sender;
     private String receiver;
     private String msg;
     private Date sendTime;

    public Talk() {
    }

    public Talk(Integer id, String sender, String receiver, String msg, Date sendTime) {
       this.id = id;
       this.sender = sender;
       this.receiver = receiver;
       this.msg = msg;
       this.sendTime = sendTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }




}


