package com.yodoo.rent.model;
// Generated 2007-8-8 15:49:53 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private String id;
     private String localPath;
     private String url;
     private String type;
     private String comment;
     private Set<HouseInfo> houseInfos = new HashSet<HouseInfo>(0);

    public Media() {
    }

	
    public Media(String type) {
        this.type = type;
    }
    public Media(String localPath, String url, String type, String comment, Set<HouseInfo> houseInfos) {
       this.localPath = localPath;
       this.url = url;
       this.type = type;
       this.comment = comment;
       this.houseInfos = houseInfos;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getLocalPath() {
        return this.localPath;
    }
    
    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<HouseInfo> getHouseInfos() {
        return this.houseInfos;
    }
    
    public void setHouseInfos(Set<HouseInfo> houseInfos) {
        this.houseInfos = houseInfos;
    }




}


