package com.yodoo.rent.model;
// Generated 2007-8-11 22:20:27 by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private Integer version;
     private String password;
     private boolean enabled;
     private String displayName;
     private Set<HouseInfo> houseInfos = new HashSet<HouseInfo>(0);
     private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);
     private Set<Role> roles = new HashSet<Role>(0);

    public User() {
    }

	
    public User(String username, String password, boolean enabled) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
    }
    public User(String username, String password, boolean enabled, String displayName, Set<HouseInfo> houseInfos, Set<UserProfile> userProfiles, Set<Role> roles) {
       this.username = username;
       this.password = password;
       this.enabled = enabled;
       this.displayName = displayName;
       this.houseInfos = houseInfos;
       this.userProfiles = userProfiles;
       this.roles = roles;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set<HouseInfo> getHouseInfos() {
        return this.houseInfos;
    }
    
    public void setHouseInfos(Set<HouseInfo> houseInfos) {
        this.houseInfos = houseInfos;
    }
    public Set<UserProfile> getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set<UserProfile> userProfiles) {
        this.userProfiles = userProfiles;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


